# Generated by Django 2.2 on 2020-09-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiondata',
            name='country',
            field=models.CharField(max_length=400),
        ),
    ]
